name: Compilar App Android

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el código
      uses: actions/checkout@v4

    - name: Forzar uso de SDK 8 (global.json)
      run: |
        echo '{
          "sdk": {
            "version": "8.0.403",
            "rollForward": "latestFeature"
          }
        }' > global.json

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.403'

    - name: Instalar Workloads
      run: dotnet workload install maui-android wasm-tools

    - name: Restaurar dependencias
      run: dotnet restore EtiquetadoAuto.csproj

    - name: Compilar APK (Release)
      # Quitamos -p:StaticWebAssetsEnabled=true que es lo que rompe el build de Blazor Hybrid
      # Usamos el comando estándar de MAUI para Android
      run: dotnet publish EtiquetadoAuto.csproj -f net8.0-android -c Release -p:AndroidKeyStore=false --no-restore

    - name: Guardar el archivo APK
      uses: actions/upload-artifact@v4
      with:
        name: LogisticaVision-APK
        path: |
          **/bin/Release/net8.0-android/*.apk
          **/bin/Release/net8.0-android/publish/*.apk