name: Compilar App Android

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el código
      uses: actions/checkout@v4

    - name: Configurar .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Instalar Workload Android
      run: dotnet workload install maui-android -p:CheckEolTargetFramework=false

    - name: Restaurar dependencias
      # Usamos --interactive por si acaso y forzamos el feed oficial directamente
      run: |
        dotnet restore EtiquetadoAuto.csproj \
          --source "https://api.nuget.org/v3/index.json" \
          -p:CheckEolTargetFramework=false

    - name: Publicar APK
      run: |
        dotnet publish EtiquetadoAuto.csproj \
          -f net8.0-android \
          -c Release \
          -p:AndroidKeyStore=false \
          -p:CheckEolTargetFramework=false \
          --no-restore

    - name: Guardar APK
      uses: actions/upload-artifact@v4
      with:
        name: Etiquetado-OCR-APK
        path: |
          **/bin/Release/net8.0-android/publish/*.apk
          **/bin/Release/net8.0-android/*.apk